//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDesign.API.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNameResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNameResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TTDesign.API.Languages.DisplayNameResource", typeof(DisplayNameResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllocationDate.
        /// </summary>
        public static string AllocationDate {
            get {
                return ResourceManager.GetString("AllocationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        public static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Category.
        /// </summary>
        public static string AssetCategory {
            get {
                return ResourceManager.GetString("AssetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Category Name.
        /// </summary>
        public static string AssetCategoryName {
            get {
                return ResourceManager.GetString("AssetCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Code.
        /// </summary>
        public static string AssetCode {
            get {
                return ResourceManager.GetString("AssetCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Component Specs.
        /// </summary>
        public static string AssetComponentSpecs {
            get {
                return ResourceManager.GetString("AssetComponentSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer Specs.
        /// </summary>
        public static string AssetComputerSpecs {
            get {
                return ResourceManager.GetString("AssetComputerSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Condition.
        /// </summary>
        public static string AssetCondition {
            get {
                return ResourceManager.GetString("AssetCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Monitor Specs.
        /// </summary>
        public static string AssetMonitorSpecs {
            get {
                return ResourceManager.GetString("AssetMonitorSpecs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Ownership Type.
        /// </summary>
        public static string AssetOwnershipType {
            get {
                return ResourceManager.GetString("AssetOwnershipType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset Status.
        /// </summary>
        public static string AssetStatus {
            get {
                return ResourceManager.GetString("AssetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Unit.
        /// </summary>
        public static string BillCurrencyUnit {
            get {
                return ResourceManager.GetString("BillCurrencyUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill Date.
        /// </summary>
        public static string BillDate {
            get {
                return ResourceManager.GetString("BillDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string BillDescription {
            get {
                return ResourceManager.GetString("BillDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string BillItem {
            get {
                return ResourceManager.GetString("BillItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill No.
        /// </summary>
        public static string BillNo {
            get {
                return ResourceManager.GetString("BillNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string BillType {
            get {
                return ResourceManager.GetString("BillType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Team.
        /// </summary>
        public static string CategoryTeamId {
            get {
                return ResourceManager.GetString("CategoryTeamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ClientCode {
            get {
                return ResourceManager.GetString("ClientCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ClientName {
            get {
                return ResourceManager.GetString("ClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigCode.
        /// </summary>
        public static string ConfigCode {
            get {
                return ResourceManager.GetString("ConfigCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConfigName.
        /// </summary>
        public static string ConfigName {
            get {
                return ResourceManager.GetString("ConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days {
            get {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DestroyDate.
        /// </summary>
        public static string DestroyDate {
            get {
                return ResourceManager.GetString("DestroyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisposeDate.
        /// </summary>
        public static string DisposeDate {
            get {
                return ResourceManager.GetString("DisposeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger Printer.
        /// </summary>
        public static string FingerPrinter {
            get {
                return ResourceManager.GetString("FingerPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string FingerPrinterDate {
            get {
                return ResourceManager.GetString("FingerPrinterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string FingerPrinterNote {
            get {
                return ResourceManager.GetString("FingerPrinterNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time In.
        /// </summary>
        public static string FingerPrinterTimeIn {
            get {
                return ResourceManager.GetString("FingerPrinterTimeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        public static string FingerPrinterTimeOut {
            get {
                return ResourceManager.GetString("FingerPrinterTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string FingerPrinterUser {
            get {
                return ResourceManager.GetString("FingerPrinterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Code.
        /// </summary>
        public static string GroupCode {
            get {
                return ResourceManager.GetString("GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Member.
        /// </summary>
        public static string GroupMember {
            get {
                return ResourceManager.GetString("GroupMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string GroupTeam {
            get {
                return ResourceManager.GetString("GroupTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string HoliadyName {
            get {
                return ResourceManager.GetString("HoliadyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday.
        /// </summary>
        public static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply for.
        /// </summary>
        public static string HolidayApply {
            get {
                return ResourceManager.GetString("HolidayApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday End Date.
        /// </summary>
        public static string HolidayEndDate {
            get {
                return ResourceManager.GetString("HolidayEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string HolidayStartDate {
            get {
                return ResourceManager.GetString("HolidayStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string HolidayType {
            get {
                return ResourceManager.GetString("HolidayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Request.
        /// </summary>
        public static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Leave.
        /// </summary>
        public static string LeaveRequest {
            get {
                return ResourceManager.GetString("LeaveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string LeaveRequestEndDate {
            get {
                return ResourceManager.GetString("LeaveRequestEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string LeaveRequestEndTime {
            get {
                return ResourceManager.GetString("LeaveRequestEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string LeaveRequestReason {
            get {
                return ResourceManager.GetString("LeaveRequestReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string LeaveRequestStartDate {
            get {
                return ResourceManager.GetString("LeaveRequestStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string LeaveRequestStartTime {
            get {
                return ResourceManager.GetString("LeaveRequestStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type.
        /// </summary>
        public static string LeaveRequestType {
            get {
                return ResourceManager.GetString("LeaveRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string Mã {
            get {
                return ResourceManager.GetString("Mã", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string Months {
            get {
                return ResourceManager.GetString("Months", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string Object {
            get {
                return ResourceManager.GetString("Object", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object Name.
        /// </summary>
        public static string ObjectName {
            get {
                return ResourceManager.GetString("ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Request.
        /// </summary>
        public static string Overtime {
            get {
                return ResourceManager.GetString("Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string OvertimeCategory {
            get {
                return ResourceManager.GetString("OvertimeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string OvertimeDate {
            get {
                return ResourceManager.GetString("OvertimeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string OvertimeDescription {
            get {
                return ResourceManager.GetString("OvertimeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string OvertimeEnd {
            get {
                return ResourceManager.GetString("OvertimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string OvertimeFrom {
            get {
                return ResourceManager.GetString("OvertimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplier.
        /// </summary>
        public static string OvertimeMultiplier {
            get {
                return ResourceManager.GetString("OvertimeMultiplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string OvertimeObject {
            get {
                return ResourceManager.GetString("OvertimeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string OvertimeProject {
            get {
                return ResourceManager.GetString("OvertimeProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string OvertimeReason {
            get {
                return ResourceManager.GetString("OvertimeReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Rule.
        /// </summary>
        public static string OvertimeRule {
            get {
                return ResourceManager.GetString("OvertimeRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string OvertimeStart {
            get {
                return ResourceManager.GetString("OvertimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string OvertimeTo {
            get {
                return ResourceManager.GetString("OvertimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string OvertimeType {
            get {
                return ResourceManager.GetString("OvertimeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductCode.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Group.
        /// </summary>
        public static string ProductGroup {
            get {
                return ResourceManager.GetString("ProductGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string ProductGroupCode {
            get {
                return ResourceManager.GetString("ProductGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProductGroupName {
            get {
                return ResourceManager.GetString("ProductGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string ProductItem {
            get {
                return ResourceManager.GetString("ProductItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry.
        /// </summary>
        public static string ProductItemExpiryDate {
            get {
                return ResourceManager.GetString("ProductItemExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial.
        /// </summary>
        public static string ProductItemSerial {
            get {
                return ResourceManager.GetString("ProductItemSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string ProductItemStartDate {
            get {
                return ResourceManager.GetString("ProductItemStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Manage Code.
        /// </summary>
        public static string ProductManageCode {
            get {
                return ResourceManager.GetString("ProductManageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species.
        /// </summary>
        public static string ProductSpecies {
            get {
                return ResourceManager.GetString("ProductSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type.
        /// </summary>
        public static string ProductType {
            get {
                return ResourceManager.GetString("ProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Type Code.
        /// </summary>
        public static string ProductTypeCode {
            get {
                return ResourceManager.GetString("ProductTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ProductTypeId {
            get {
                return ResourceManager.GetString("ProductTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string ProductTypeName {
            get {
                return ResourceManager.GetString("ProductTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Client.
        /// </summary>
        public static string ProjectClient {
            get {
                return ResourceManager.GetString("ProjectClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Code.
        /// </summary>
        public static string ProjectCode {
            get {
                return ResourceManager.GetString("ProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectContract.
        /// </summary>
        public static string ProjectContract {
            get {
                return ResourceManager.GetString("ProjectContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectContractCode.
        /// </summary>
        public static string ProjectContractCode {
            get {
                return ResourceManager.GetString("ProjectContractCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish Date.
        /// </summary>
        public static string ProjectFinish {
            get {
                return ResourceManager.GetString("ProjectFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string ProjectGroup {
            get {
                return ResourceManager.GetString("ProjectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Manager.
        /// </summary>
        public static string ProjectManager {
            get {
                return ResourceManager.GetString("ProjectManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Hours.
        /// </summary>
        public static string ProjectQuotation {
            get {
                return ResourceManager.GetString("ProjectQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string ProjectStart {
            get {
                return ResourceManager.GetString("ProjectStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Status.
        /// </summary>
        public static string ProjectStatus {
            get {
                return ResourceManager.GetString("ProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Team.
        /// </summary>
        public static string ProjectTeam {
            get {
                return ResourceManager.GetString("ProjectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type.
        /// </summary>
        public static string ProjectType {
            get {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PurchaseDate.
        /// </summary>
        public static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap Day.
        /// </summary>
        public static string SwapDay {
            get {
                return ResourceManager.GetString("SwapDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string SwapDayDescription {
            get {
                return ResourceManager.GetString("SwapDayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string SwapDayFromDate {
            get {
                return ResourceManager.GetString("SwapDayFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string SwapDayToDate {
            get {
                return ResourceManager.GetString("SwapDayToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string SwapDayUserId {
            get {
                return ResourceManager.GetString("SwapDayUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Task Name.
        /// </summary>
        public static string TaskName {
            get {
                return ResourceManager.GetString("TaskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Code.
        /// </summary>
        public static string TeamCode {
            get {
                return ResourceManager.GetString("TeamCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Name.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet.
        /// </summary>
        public static string Timesheet {
            get {
                return ResourceManager.GetString("Timesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TimesheetCategory {
            get {
                return ResourceManager.GetString("TimesheetCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string TimesheetDescription {
            get {
                return ResourceManager.GetString("TimesheetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string TimesheetHour {
            get {
                return ResourceManager.GetString("TimesheetHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        public static string TimesheetObject {
            get {
                return ResourceManager.GetString("TimesheetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string TimesheetProject {
            get {
                return ResourceManager.GetString("TimesheetProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransferDate.
        /// </summary>
        public static string TransferDate {
            get {
                return ResourceManager.GetString("TransferDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string UserAboutMe {
            get {
                return ResourceManager.GetString("UserAboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAccountBank.
        /// </summary>
        public static string UserAccountBank {
            get {
                return ResourceManager.GetString("UserAccountBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string UserAddress {
            get {
                return ResourceManager.GetString("UserAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Bank Name.
        /// </summary>
        public static string UserBankName {
            get {
                return ResourceManager.GetString("UserBankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string UserBirthday {
            get {
                return ResourceManager.GetString("UserBirthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Dependent.
        /// </summary>
        public static string UserDependent {
            get {
                return ResourceManager.GetString("UserDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger ID.
        /// </summary>
        public static string UserFingerId {
            get {
                return ResourceManager.GetString("UserFingerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string UserFullName {
            get {
                return ResourceManager.GetString("UserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string UserGender {
            get {
                return ResourceManager.GetString("UserGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID No.
        /// </summary>
        public static string UserIdNo {
            get {
                return ResourceManager.GetString("UserIdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued By.
        /// </summary>
        public static string UserIssuedBy {
            get {
                return ResourceManager.GetString("UserIssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued To.
        /// </summary>
        public static string UserIssuedTo {
            get {
                return ResourceManager.GetString("UserIssuedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string UserPhoneNumber {
            get {
                return ResourceManager.GetString("UserPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string UserPosition {
            get {
                return ResourceManager.GetString("UserPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User report.
        /// </summary>
        public static string UserReport {
            get {
                return ResourceManager.GetString("UserReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Notification.
        /// </summary>
        public static string UserSettingEmailNotification {
            get {
                return ResourceManager.GetString("UserSettingEmailNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string UserSettingLanguage {
            get {
                return ResourceManager.GetString("UserSettingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone.
        /// </summary>
        public static string UserSettingTimeZone {
            get {
                return ResourceManager.GetString("UserSettingTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Insurance Book No.
        /// </summary>
        public static string UserSocialInsuranceBookNo {
            get {
                return ResourceManager.GetString("UserSocialInsuranceBookNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID.
        /// </summary>
        public static string UserStaffId {
            get {
                return ResourceManager.GetString("UserStaffId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Start Work.
        /// </summary>
        public static string UserStartWork {
            get {
                return ResourceManager.GetString("UserStartWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string UserState {
            get {
                return ResourceManager.GetString("UserState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string UserTask {
            get {
                return ResourceManager.GetString("UserTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        public static string UserTeam {
            get {
                return ResourceManager.GetString("UserTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work From Home.
        /// </summary>
        public static string Wfh {
            get {
                return ResourceManager.GetString("Wfh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string WfhEnd {
            get {
                return ResourceManager.GetString("WfhEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        public static string WfhReason {
            get {
                return ResourceManager.GetString("WfhReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string WfhStart {
            get {
                return ResourceManager.GetString("WfhStart", resourceCulture);
            }
        }
    }
}
