//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDesign.API.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TTDesign.API.Languages.ErrorMessageResource", typeof(ErrorMessageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not accept invitation.
        /// </summary>
        public static string AcceptInvitationError {
            get {
                return ResourceManager.GetString("AcceptInvitationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File input must png/img.
        /// </summary>
        public static string AvatarExtension {
            get {
                return ResourceManager.GetString("AvatarExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar null.
        /// </summary>
        public static string AvatarNull {
            get {
                return ResourceManager.GetString("AvatarNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File over 5MB.
        /// </summary>
        public static string AvatarOverSize {
            get {
                return ResourceManager.GetString("AvatarOverSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill had sync.
        /// </summary>
        public static string BillHadSyncError {
            get {
                return ResourceManager.GetString("BillHadSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item had using in this bill.
        /// </summary>
        public static string BillItemHadUsing {
            get {
                return ResourceManager.GetString("BillItemHadUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product quantity has be greater than 0.
        /// </summary>
        public static string BillProductQuantityError {
            get {
                return ResourceManager.GetString("BillProductQuantityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object not found.
        /// </summary>
        public static string CalendarObjectNotFound {
            get {
                return ResourceManager.GetString("CalendarObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not log timesheet in holiday.
        /// </summary>
        public static string CanNotLogTimesheetInHoliday {
            get {
                return ResourceManager.GetString("CanNotLogTimesheetInHoliday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password wrong.
        /// </summary>
        public static string ChangePasswordFail {
            get {
                return ResourceManager.GetString("ChangePasswordFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not change status.
        /// </summary>
        public static string ChangeStatusError {
            get {
                return ResourceManager.GetString("ChangeStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature is coming soon....
        /// </summary>
        public static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date not allow future.
        /// </summary>
        public static string DateFutureError {
            get {
                return ResourceManager.GetString("DateFutureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date End is past of Date Start.
        /// </summary>
        public static string DatePastError {
            get {
                return ResourceManager.GetString("DatePastError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date over range (past over 2 month and furture).
        /// </summary>
        public static string DateRangeError {
            get {
                return ResourceManager.GetString("DateRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime input wrong format (yyyy/MM/dd HH:mm).
        /// </summary>
        public static string DateWrongFormat {
            get {
                return ResourceManager.GetString("DateWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not delete product, which has item belong.
        /// </summary>
        public static string DeleteProductHadItem {
            get {
                return ResourceManager.GetString("DeleteProductHadItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File input must pdf/excel/docx/image.
        /// </summary>
        public static string DocumentExtension {
            get {
                return ResourceManager.GetString("DocumentExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document count over 5 files.
        /// </summary>
        public static string DocumentMaximumError {
            get {
                return ResourceManager.GetString("DocumentMaximumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not found.
        /// </summary>
        public static string DocumentNull {
            get {
                return ResourceManager.GetString("DocumentNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File over 5MB.
        /// </summary>
        public static string DocumentOverSize {
            get {
                return ResourceManager.GetString("DocumentOverSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status asset don&apos;t allocate.
        /// </summary>
        public static string ErrorAllocateAssetStatus {
            get {
                return ResourceManager.GetString("ErrorAllocateAssetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete a task in the current state..
        /// </summary>
        public static string ErrorDeleteTask {
            get {
                return ResourceManager.GetString("ErrorDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Id is wrong.
        /// </summary>
        public static string ErrorTenant {
            get {
                return ResourceManager.GetString("ErrorTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not found.
        /// </summary>
        public static string ExistFieldError {
            get {
                return ResourceManager.GetString("ExistFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Current had exist.
        /// </summary>
        public static string ExistStatusError {
            get {
                return ResourceManager.GetString("ExistStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration Time.
        /// </summary>
        public static string Exp {
            get {
                return ResourceManager.GetString("Exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} had exist.
        /// </summary>
        public static string HadExistError {
            get {
                return ResourceManager.GetString("HadExistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} had locked.
        /// </summary>
        public static string HadLocked {
            get {
                return ResourceManager.GetString("HadLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} had using.
        /// </summary>
        public static string HadUsing {
            get {
                return ResourceManager.GetString("HadUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday must this year or furture.
        /// </summary>
        public static string HolidayDateRangeError {
            get {
                return ResourceManager.GetString("HolidayDateRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not allow input past date.
        /// </summary>
        public static string InputPastDateError {
            get {
                return ResourceManager.GetString("InputPastDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong value input {0}.
        /// </summary>
        public static string InvalidError {
            get {
                return ResourceManager.GetString("InvalidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data type for the specified field {0}..
        /// </summary>
        public static string InvalidFieldType {
            get {
                return ResourceManager.GetString("InvalidFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave request {1} must multiples of {2}.
        /// </summary>
        public static string LeaveRequestBlockError {
            get {
                return ResourceManager.GetString("LeaveRequestBlockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date request must Time Work weekday.
        /// </summary>
        public static string LeaveRequestTimeWorkError {
            get {
                return ResourceManager.GetString("LeaveRequestTimeWorkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have had {1} leave requests in the past 30 days..
        /// </summary>
        public static string LeaveSelfWeddingError {
            get {
                return ResourceManager.GetString("LeaveSelfWeddingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acount is inactive.
        /// </summary>
        public static string LoginEmailInactive {
            get {
                return ResourceManager.GetString("LoginEmailInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not found.
        /// </summary>
        public static string LoginEmailNotFound {
            get {
                return ResourceManager.GetString("LoginEmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is wrong.
        /// </summary>
        public static string LoginWrongPassword {
            get {
                return ResourceManager.GetString("LoginWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request leave {1} must lefter than {2} {3}.
        /// </summary>
        public static string MaximumPeriodLeaveError {
            get {
                return ResourceManager.GetString("MaximumPeriodLeaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length of {0} is {1} character.
        /// </summary>
        public static string MaxLengthError {
            get {
                return ResourceManager.GetString("MaxLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar must lefter than 15&apos;.
        /// </summary>
        public static string MinimumPeriodCalendarError {
            get {
                return ResourceManager.GetString("MinimumPeriodCalendarError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request leave {1} must longer than {2} {3}.
        /// </summary>
        public static string MinimumPeriodLeaveError {
            get {
                return ResourceManager.GetString("MinimumPeriodLeaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request time must longer than 15 minutes.
        /// </summary>
        public static string MinimumPeriodOvertimeError {
            get {
                return ResourceManager.GetString("MinimumPeriodOvertimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request time must longer than 4 hours.
        /// </summary>
        public static string MinimumPeriodWfhError {
            get {
                return ResourceManager.GetString("MinimumPeriodWfhError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not before time.
        /// </summary>
        public static string Nbf {
            get {
                return ResourceManager.GetString("Nbf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number input must positive number.
        /// </summary>
        public static string NumberInputError {
            get {
                return ResourceManager.GetString("NumberInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request leave {1} over left remain leave {2} {3}.
        /// </summary>
        public static string OverRemainLeaveError {
            get {
                return ResourceManager.GetString("OverRemainLeaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM must is member of once Group.
        /// </summary>
        public static string PMNotFound {
            get {
                return ResourceManager.GetString("PMNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not update Product status Unavailable.
        /// </summary>
        public static string ProductAvailableError {
            get {
                return ResourceManager.GetString("ProductAvailableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not update status Unavailable when has item available.
        /// </summary>
        public static string ProductChangeStatusError {
            get {
                return ResourceManager.GetString("ProductChangeStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not update Product Item status OutStock.
        /// </summary>
        public static string ProductItemOutStock {
            get {
                return ResourceManager.GetString("ProductItemOutStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can only be greater than 1 when managed by product code.
        /// </summary>
        public static string ProductTypeQuantityError {
            get {
                return ResourceManager.GetString("ProductTypeQuantityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        public static string RequiredError {
            get {
                return ResourceManager.GetString("RequiredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User only a team.
        /// </summary>
        public static string SetUserTeam {
            get {
                return ResourceManager.GetString("SetUserTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swap to date {0}.
        /// </summary>
        public static string SwapMessage {
            get {
                return ResourceManager.GetString("SwapMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total hours input over worktime.
        /// </summary>
        public static string TaskHourInputOverError {
            get {
                return ResourceManager.GetString("TaskHourInputOverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team had member.
        /// </summary>
        public static string TeamHadUserInclude {
            get {
                return ResourceManager.GetString("TeamHadUserInclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a weekday, please.
        /// </summary>
        public static string TimeMustWeekday {
            get {
                return ResourceManager.GetString("TimeMustWeekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a weekend, please.
        /// </summary>
        public static string TimeMustWeekend {
            get {
                return ResourceManager.GetString("TimeMustWeekend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be unique.
        /// </summary>
        public static string UniquedError {
            get {
                return ResourceManager.GetString("UniquedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not update bill, which has used item.
        /// </summary>
        public static string UpdateBillPendingError {
            get {
                return ResourceManager.GetString("UpdateBillPendingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not permission!.
        /// </summary>
        public static string UserNotPermission {
            get {
                return ResourceManager.GetString("UserNotPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not work in project.
        /// </summary>
        public static string UserNotWorkingProject {
            get {
                return ResourceManager.GetString("UserNotWorkingProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position can not be greater than user login position.
        /// </summary>
        public static string UserPositionError {
            get {
                return ResourceManager.GetString("UserPositionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create task with current status..
        /// </summary>
        public static string UserTaskStatus {
            get {
                return ResourceManager.GetString("UserTaskStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is expired.
        /// </summary>
        public static string VerifiedTokenError {
            get {
                return ResourceManager.GetString("VerifiedTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task work over 8 hours.
        /// </summary>
        public static string WorkTimeOverError {
            get {
                return ResourceManager.GetString("WorkTimeOverError", resourceCulture);
            }
        }
    }
}
