//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDesign.API.Languages.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TTDesign.API.Languages.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category had using.
        /// </summary>
        public static string CATEGORY_HAS_USING {
            get {
                return ResourceManager.GetString("CATEGORY_HAS_USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name is exist.
        /// </summary>
        public static string CATEGORY_NAME_EXIST {
            get {
                return ResourceManager.GetString("CATEGORY_NAME_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category not found.
        /// </summary>
        public static string CATEGORY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CATEGORY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create success!.
        /// </summary>
        public static string CREATE_TEAM_SUCCESS {
            get {
                return ResourceManager.GetString("CREATE_TEAM_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create success!.
        /// </summary>
        public static string CREATE_USER_SUCCESS {
            get {
                return ResourceManager.GetString("CREATE_USER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data invalid.
        /// </summary>
        public static string DATA_INVALID {
            get {
                return ResourceManager.GetString("DATA_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field had required!.
        /// </summary>
        public static string DATA_REQUIRE {
            get {
                return ResourceManager.GetString("DATA_REQUIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date End is past of Date Start.
        /// </summary>
        public static string DATE_END_PAST_START {
            get {
                return ResourceManager.GetString("DATE_END_PAST_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime input wrong format (yyyy/MM/dd HH:mm).
        /// </summary>
        public static string DATE_INPUT_WRONG_FORMAT {
            get {
                return ResourceManager.GetString("DATE_INPUT_WRONG_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date over range.
        /// </summary>
        public static string DATE_RANGE_ERROR {
            get {
                return ResourceManager.GetString("DATE_RANGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email had exist!.
        /// </summary>
        public static string EMAIL_HAD_EXIST {
            get {
                return ResourceManager.GetString("EMAIL_HAD_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does not existed!.
        /// </summary>
        public static string EMAIL_NOT_FOUND {
            get {
                return ResourceManager.GetString("EMAIL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An issue occurred, please try again!.
        /// </summary>
        public static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File input must png/img.
        /// </summary>
        public static string FILE_AVATAR_EXTENSION {
            get {
                return ResourceManager.GetString("FILE_AVATAR_EXTENSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File over 5MB.
        /// </summary>
        public static string FILE_AVATAR_OVER_SIZE {
            get {
                return ResourceManager.GetString("FILE_AVATAR_OVER_SIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select file.
        /// </summary>
        public static string FILE_NULL {
            get {
                return ResourceManager.GetString("FILE_NULL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger ID has exist.
        /// </summary>
        public static string FINGER_ID_DUPLICATE {
            get {
                return ResourceManager.GetString("FINGER_ID_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger Printer had exist.
        /// </summary>
        public static string FINGER_PRINTER_HAD_EXIST {
            get {
                return ResourceManager.GetString("FINGER_PRINTER_HAD_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date had lock.
        /// </summary>
        public static string FINGER_PRINTER_HAD_LOCK {
            get {
                return ResourceManager.GetString("FINGER_PRINTER_HAD_LOCK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finger Printer not found.
        /// </summary>
        public static string FINGERPRINTER_NOT_FOUND {
            get {
                return ResourceManager.GetString("FINGERPRINTER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group code has exist!.
        /// </summary>
        public static string GROUP_CODE_EXIST {
            get {
                return ResourceManager.GetString("GROUP_CODE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group not found!.
        /// </summary>
        public static string GROUP_NOT_FOUND {
            get {
                return ResourceManager.GetString("GROUP_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users had belong team.
        /// </summary>
        public static string HAD_USER_BELONG_TEAM {
            get {
                return ResourceManager.GetString("HAD_USER_BELONG_TEAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has user using this role.
        /// </summary>
        public static string HAD_USER_USING_ROLE {
            get {
                return ResourceManager.GetString("HAD_USER_USING_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holiday not found.
        /// </summary>
        public static string HOLIDAY_NOT_FOUND {
            get {
                return ResourceManager.GetString("HOLIDAY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong value input.
        /// </summary>
        public static string INVALID_ERROR {
            get {
                return ResourceManager.GetString("INVALID_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Least common multiple of holiday is 4 hours.
        /// </summary>
        public static string LEAST_COMMON_MULTIPLE_HOLIDAY_WRONG {
            get {
                return ResourceManager.GetString("LEAST_COMMON_MULTIPLE_HOLIDAY_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object had using.
        /// </summary>
        public static string OBJECT_HAS_USING {
            get {
                return ResourceManager.GetString("OBJECT_HAS_USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object name is exist!.
        /// </summary>
        public static string OBJECT_NAME_EXIST {
            get {
                return ResourceManager.GetString("OBJECT_NAME_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object not found.
        /// </summary>
        public static string OBJECT_NOT_FOUND {
            get {
                return ResourceManager.GetString("OBJECT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime request not found.
        /// </summary>
        public static string OVERTIME_NOT_FOUND {
            get {
                return ResourceManager.GetString("OVERTIME_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request OT had duplidate.
        /// </summary>
        public static string OVERTIME_REQUEST_DUPLICATE {
            get {
                return ResourceManager.GetString("OVERTIME_REQUEST_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password input wrong.
        /// </summary>
        public static string PASSWORD_INPUT_WRONG {
            get {
                return ResourceManager.GetString("PASSWORD_INPUT_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position input wrong!.
        /// </summary>
        public static string POSITION_INPUT_WRONG {
            get {
                return ResourceManager.GetString("POSITION_INPUT_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project had using.
        /// </summary>
        public static string PROJECT_HAD_USING {
            get {
                return ResourceManager.GetString("PROJECT_HAD_USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not found.
        /// </summary>
        public static string PROJECT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PROJECT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role had using.
        /// </summary>
        public static string ROLE_HAS_USING {
            get {
                return ResourceManager.GetString("ROLE_HAS_USING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found!.
        /// </summary>
        public static string ROLE_INPUT_WRONG {
            get {
                return ResourceManager.GetString("ROLE_INPUT_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role name has exist.
        /// </summary>
        public static string ROLE_NAME_EXIST {
            get {
                return ResourceManager.GetString("ROLE_NAME_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found!.
        /// </summary>
        public static string ROLE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ROLE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff ID has exist.
        /// </summary>
        public static string STAFF_ID_DUPLICATE {
            get {
                return ResourceManager.GetString("STAFF_ID_DUPLICATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State not found.
        /// </summary>
        public static string STATE_NOT_FOUND {
            get {
                return ResourceManager.GetString("STATE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TeamCode had exist!.
        /// </summary>
        public static string TEAM_CODE_EXIST {
            get {
                return ResourceManager.GetString("TEAM_CODE_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team had leader!.
        /// </summary>
        public static string TEAM_HAS_LEADER {
            get {
                return ResourceManager.GetString("TEAM_HAS_LEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team not found!.
        /// </summary>
        public static string TEAM_NOT_FOUND {
            get {
                return ResourceManager.GetString("TEAM_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update success!.
        /// </summary>
        public static string UPDATE_TEAM_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_TEAM_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update success!.
        /// </summary>
        public static string UPDATE_USER_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_USER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload avatar successfully!.
        /// </summary>
        public static string UPLOAD_AVATAR_SUCCESS {
            get {
                return ResourceManager.GetString("UPLOAD_AVATAR_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is inactive.
        /// </summary>
        public static string USER_INACTIVE {
            get {
                return ResourceManager.GetString("USER_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User invalid.
        /// </summary>
        public static string USER_INVALID {
            get {
                return ResourceManager.GetString("USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found!.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not handle action.
        /// </summary>
        public static string USER_NOT_HANDLE {
            get {
                return ResourceManager.GetString("USER_NOT_HANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not permission!.
        /// </summary>
        public static string USER_NOT_PERMISSION {
            get {
                return ResourceManager.GetString("USER_NOT_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not working project.
        /// </summary>
        public static string USER_NOT_WORKING_PROJECT {
            get {
                return ResourceManager.GetString("USER_NOT_WORKING_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is not correct so you can not make your change. Please check your password again!.
        /// </summary>
        public static string USER_PASSWORD_NOT_EQUAL {
            get {
                return ResourceManager.GetString("USER_PASSWORD_NOT_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status input wrong!.
        /// </summary>
        public static string USER_STATUS_INPUT_WRONG {
            get {
                return ResourceManager.GetString("USER_STATUS_INPUT_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team role input wrong!.
        /// </summary>
        public static string USER_TEAM_ROLE_INPUT_WRONG {
            get {
                return ResourceManager.GetString("USER_TEAM_ROLE_INPUT_WRONG", resourceCulture);
            }
        }
    }
}
