//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTDesign.API.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TTDesign.API.Languages.Resource - Copy", typeof(Resource___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data require.
        /// </summary>
        public static string DATA_REQUIRE {
            get {
                return ResourceManager.GetString("DATA_REQUIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email had exist!.
        /// </summary>
        public static string EMAIL_HAD_EXIST {
            get {
                return ResourceManager.GetString("EMAIL_HAD_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email does not existed!.
        /// </summary>
        public static string EMAIL_NOT_FOUND {
            get {
                return ResourceManager.GetString("EMAIL_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password input wrong.
        /// </summary>
        public static string PASSWORD_INPUT_WRONG {
            get {
                return ResourceManager.GetString("PASSWORD_INPUT_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found!.
        /// </summary>
        public static string ROLE_INPUT_WRONG {
            get {
                return ResourceManager.GetString("ROLE_INPUT_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update success!.
        /// </summary>
        public static string UPDATE_USER_SUCCESS {
            get {
                return ResourceManager.GetString("UPDATE_USER_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload avatar successfully!.
        /// </summary>
        public static string UPLOAD_AVATAR_SUCCESS {
            get {
                return ResourceManager.GetString("UPLOAD_AVATAR_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found!.
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not permission!.
        /// </summary>
        public static string USER_NOT_PERMISSION {
            get {
                return ResourceManager.GetString("USER_NOT_PERMISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not working project.
        /// </summary>
        public static string USER_NOT_WORKING_PROJECT {
            get {
                return ResourceManager.GetString("USER_NOT_WORKING_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is not correct so you can not make your change. Please check your password again!.
        /// </summary>
        public static string USER_PASSWORD_NOT_EQUAL {
            get {
                return ResourceManager.GetString("USER_PASSWORD_NOT_EQUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role input wrong!.
        /// </summary>
        public static string USER_ROLE_INPUT_WRONG {
            get {
                return ResourceManager.GetString("USER_ROLE_INPUT_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status input wrong!.
        /// </summary>
        public static string USER_STATUS_INPUT_WRONG {
            get {
                return ResourceManager.GetString("USER_STATUS_INPUT_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team role input wrong!.
        /// </summary>
        public static string USER_TEAM_ROLE_INPUT_WRONG {
            get {
                return ResourceManager.GetString("USER_TEAM_ROLE_INPUT_WRONG", resourceCulture);
            }
        }
    }
}
